[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = "shanghai"

[rpc_endpoints]
fuji-c = "https://api.avax-test.network/ext/bc/C/rpc"
dispatch = "https://subnets.avax.network/dispatch/testnet/rpc"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
